### ISSUE TITLE
"syntax error in expression" random error

### ISSUE THREAD

**Issue by iRomanyshyn** [selivan/https-ssl-cert-check-zabbix#11]
Hi! Thank you for this script! It's exactly what I searched for. But it keeps to show the error at random time in my situation when I try to check validity of monitored service's SSL certificate. The errors looks like this:
`./ssl_cert_check.sh: line 85: [[: 0
0
0: syntax error in expression (error token is "0
0")
0`
I would like to check it without the script if needed, but I can't give an access to that service, because it's internal. Anyway, thank you.

**Comment by selivan** [comment]
Hi!

Could you please send output of these commands:

```
openssl version

openssl s_client -CApath "/etc/ssl/certs" -servername "$domain" -verify_hostname "$domain" -connect "$host":"$port"
```

Where `$domain` is checked service DNS name, and `$host` and `$port` are host address(probably same as `$domain`) and port number.

**Comment by iRomanyshyn** [comment]
Sure!
`OpenSSL 1.1.1f  31 Mar 2020
`
`CONNECTED(00000003)
---
Certificate chain
 0 s:CN = *.example.com
   i:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
 1 s:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
   i:C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
 2 s:C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
   i:C = GB, ST = Greater Manchester, L = Salford, O = Comodo CA Limited, CN = AAA Certificate Services
 3 s:C = GB, ST = Greater Manchester, L = Salford, O = Comodo CA Limited, CN = AAA Certificate Services
   i:C = GB, ST = Greater Manchester, L = Salford, O = Comodo CA Limited, CN = AAA Certificate Services
---
Server certificate
-----BEGIN CERTIFICATE-----
***
-----END CERTIFICATE-----
subject=CN = *.example.com

issuer=C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 6083 bytes and written 390 bytes
Verification: OK
Verified peername: *.example.com
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: ***
    Session-ID-ctx: 
    Resumption PSK: ***
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    ***

    Start Time: 1604359703
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: ***
    Session-ID-ctx: 
    Resumption PSK: ***
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    ***

    Start Time: 1604359703
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
closed`

Thanks for quick reply!

**Comment by selivan** [comment]
Could you please check if the script from this branch works? https://raw.githubusercontent.com/selivan/https-ssl-cert-check-zabbix/small_improvements/ssl_cert_check.sh

When you post code on github, I recommend to enclose it with markdown code markers - triple backtick: ``` Otherwise github parses it as markdown.

**Comment by iRomanyshyn** [comment]
```
./ssl_cert_check.sh: command substitution: line 85: syntax error near unexpected token `|'
./ssl_cert_check.sh: command substitution: line 85: ` echo "$output" | grep -E '^Verify return code:' | sed -n 1p | | tr -s ' ' | cut -d' ' -f4 )'
```

**Comment by selivan** [comment]
Ops, a typo when saving file. Check it again please: https://raw.githubusercontent.com/selivan/https-ssl-cert-check-zabbix/small_improvements/ssl_cert_check.sh

**Comment by iRomanyshyn** [comment]
Looks like the error is gone.

**Comment by selivan** [comment]
New openssl was printing multiple return codes for post-handshake session tickets, script wasn't expecting that.

Thanks for the bug report.

**Comment by iRomanyshyn** [comment]
Thank you!
