### ISSUE TITLE
Unsupported Zabbix Item when certificate errors occur (due to stderr)

### ISSUE THREAD

**Issue by timwsuqld** [selivan/https-ssl-cert-check-zabbix#13]
### Environment

`openssl version` says:

```
OpenSSL 1.1.1  11 Sep 2018
```

Operating System:  Ubuntu 18.04 (Zabbix)

### Expected Behavior
When a certificate error occurs, using Zabbix UserParameter, we should get -65535 as the result in Zabbix

### Current Behavior
When a certificate error occurs, using Zabbix UserParameter, we get an unsupported item in Zabbix due to the stderr message.
As stated at https://www.zabbix.com/documentation/3.0/manual/config/items/userparameters, ` The return value of the command is standard output together with standard error. `. This means we need a way to run `ssl_cert_check.sh` without errors on stderr breaking the code.

### Details

We need an extra flag for `ssl_cert_check.sh` when used with Zabbix so that we don't cause unsupported item errors, but can still get a meaningful message when run manually.

**Comment by selivan** [comment]
Good catch, thanks!

I don't want to lose readable error message, so here is the fix: 29003c9156955decebf184dd5b89d37c4c4593e6

When running on terminal, error message is shown to stderr, without terminal(from zabbix) it is not.
