### ISSUE TITLE
The script doesn't work on Debian8

### ISSUE THREAD

**Issue by mberthault** [selivan/https-ssl-cert-check-zabbix#24]
Hi,
1st of all, you script is exactly what I was looking for, it works like a charm on debian 9 and 10.

But I have some debian 8 and older servers, and on these ones, the script refuses to work :/

### Environment

`openssl version` says: `OpenSSL 1.0.1t  3 May 2016`

Operating System: Debian GNU/Linux 8.10 (jessie)

### Expected Behavior

```
root@yyyyy:/yyy/yyy/yyy# ./ssl_cert_check.sh expire yahoo.fr
136
```

### Current Behavior

```
root@xxxxxx:/xxx/xxx/xxx# ./ssl_cert_check.sh expire yahoo.fr
-65535
ERROR: Failed to get certificate
```

### Diagnostics
I use yahoo.fr for the example. IRL, I use my real domain.

- On my Debian 9 server, the script works, and the openssl version is: `OpenSSL 1.1.0l  10 Sep 2019`

- On my Debian 8 server, the script doesn't work and the openssl version is: `OpenSSL 1.0.1t  3 May 2016`

### Details

On the debian 8 server, I tried this:

`root@demo:/var/lib/zabbix# bash -x ./ssl_cert_check.sh expire yahoo.fr`

=> The result is:
```

+ default_check_timeout=5
+ error_code=-65535
+ check_type=expire
+ host=yahoo.fr
+ port=443
+ domain=yahoo.fr
+ check_timeout=5
+ starttls=
+ starttls_proto=
+ IFS=/
+ split=($port)
+ '[' 1 -gt 1 ']'
+ for util in timeout openssl date
+ type timeout
+ for util in timeout openssl date
+ type openssl
+ for util in timeout openssl date
+ type date
+ grep -qi busybox
+ date --version
+ '[' 2 -lt 2 ']'
+ '[' expire = expire ']'
+ [[ 443 =~ ^[0-9]+$ ]]
+ '[' 443 -ge 1 ']'
+ '[' 443 -le 65535 ']'
+ '[' '!' -z '' ']'
+ [[ 5 =~ ^[0-9]+$ ]]
++ timeout 5 openssl s_client -servername yahoo.fr -verify_hostname yahoo.fr -connect yahoo.fr:443
++ echo
+ output=
+ error 'Failed to get certificate'
+ echo -65535
-65535
+ '[' -t 1 ']'
+ echo 'ERROR: Failed to get certificate'
ERROR: Failed to get certificate
+ exit 0

```

- I then tried this:
`openssl s_client -servername yahoo.fr -verify_hostname yahoo.fr -connect yahoo.fr:443`

And I got this result:

```
unknown option -verify_hostname
usage: s_client args
```

My opinion is that the old versions of openssl doesn't support this option, and this causes the script to fail.

Maybe it would be possible to modify the script in a way that would be backwards compatible with the old ways.

Thanks a lot

Mathieu

**Comment by mberthault** [comment]
I have made a little adjustment on your script, and I find it to work very well.

I'll attach the "new version" here

My adjustment is simple (and dirty, I would say). I changed the "get certificate part into:

```

# Get certificate
if ! output=$( echo \
| timeout "$check_timeout" openssl s_client $starttls $starttls_proto -servername "$domain" -verify_hostname "$domain" -connect "$host":"$port" 2>/dev/null )
then
    if ! output=$( echo \
| timeout "$check_timeout" openssl s_client $starttls $starttls_proto -servername "$domain" -connect "$host":"$port" 2>/dev/null )
	then
	error "Failed to get certificate"
	fi
fi

```
[ssl_cert_check .txt](https://github.com/selivan/https-ssl-cert-check-zabbix/files/6448460/ssl_cert_check.txt)



For now, it seems to work, and for me it is good enough, but it could not be good for other people.

PS : pardon my english, I'm french :-p

**Comment by selivan** [comment]
Hey @mberthault 

Your patch breaks the timeout setting, if the error is not because of old openssl not recognising an option, then the timeout will double. I suppose this way to do that:

```bash
if openssl s_client --help 2>&1 | grep -q -- -verify_hostname ; then
...
else
...
```

Anyway, Debian 8 is out of LTS support at [30 June 2020](https://en.wikipedia.org/wiki/Debian_version_history#Release_table), so I don't see much use in supporting old openssl version in it.

P. S. I bet half of people here on Github have learned English as a second language, so they speak no better than you of me(Russian), nothing to apologize for :)

**Comment by mberthault** [comment]
Hi,
Thank you very much for your idea! I hadn't even thought of it. I'll try it ASAP :p

As for the Debian 8 support, I'm with you 100%, but my clients have their own ways :)

Thx again :)

**Comment by mberthault** [comment]
What do you think of this?
```

# Get certificate

if openssl s_client --help 2>&1 | grep -q -- -verify_hostname
then
  if ! output=$( echo \
| timeout "$check_timeout" openssl s_client $starttls $starttls_proto -servername "$domain" -verify_hostname "$domain" -connect "$host":"$port" 2>/dev/null )
  then
	error "Failed to get certificate"
  fi
else
  if ! output=$( echo \
| timeout "$check_timeout" openssl s_client $starttls $starttls_proto -servername "$domain" -connect "$host":"$port" 2>/dev/null )
  then
	  error "Failed to get certificate (old openssl version)"
  fi
fi

```

**Comment by selivan** [comment]
Looks fine to me. Glad to see that your issue is solved :+1: 

I am not going to complicate the script with workaround for old almost out-of-use openssl versions. Closing this one.

**Comment by mberthault** [comment]
Again, thank you for your help, and kudos for this great script :-)
