### ISSUE TITLE
Always returning 0 on validate

### ISSUE THREAD

**Issue by pedrosanta** [selivan/https-ssl-cert-check-zabbix#26]
Hello,

When doing `validate` it always returns 0—`expire` seems to be working fine. Even on google.com, etc. I've debugged with `bash -x` and the return code is 20:

```
Verify return code: 20 (unable to get local issuer certificate)
```

Full log here: https://pastebin.com/AssESEf3

Any suggestion on what might I be doing wrong? Bug maybe?

Thank you in advance.

**Comment by selivan** [comment]
Hi.

Output says:

`Verify return code: 20 (unable to get local issuer certificate)`

Your openssl installation considers google.com certificate invalid.

**Comment by iRomanyshyn** [comment]
@pedrosanta hi! Maybe, you just have a wrong date and time on your device?

**Comment by selivan** [comment]
I close the issue, this is not a problem with the code.

**Comment by pedrosanta** [comment]
It seems fairly updated, though now I notice I don't have NTP set up.

```
$ timedatectl
Local time: Tue 2021-06-08 14:36:05 UTC
Universal time: Tue 2021-06-08 14:36:05 UTC
RTC time: Tue 2021-06-08 14:36:06
Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
NTP service: inactive
RTC in local TZ: no
```

Will try to setup NTP and check again.

**Comment by selivan** [comment]
@pedrosanta You have to make 

`openssl s_client -servername google.com -verify_hostname google.com -connect google.com:443`

work with `Verify return code: 0`.

Whatever the issue is.
