### ISSUE TITLE
Multiple sites on one server ( Macros specify domains )

### ISSUE THREAD

**Issue by jvalters** [selivan/https-ssl-cert-check-zabbix#28]
Hello, this is not like a bug, but maybe it is possible to create, that in Macros you can specify domains witch needs to be monitored for SSL expireation since some people use 1 server and host 3-4 websites with SSL. 

Thanks.

**Comment by selivan** [comment]
This can de done with autodiscovery, getting multiple hosts to check from config file.

Here is an example: https://github.com/selivan/https-ssl-cert-check-zabbix/tree/master/zabbix_template_examples/advanced

**Comment by selivan** [comment]
Hope this helped. Please feel free to re-open the issue if this does not solve it for you.
