### ISSUE TITLE
Add support Russian domains

### ISSUE THREAD

**Issue by Dmitrius7** [selivan/https-ssl-cert-check-zabbix#30]
Hello!

I modyfied your script ssl_cert_check.sh. Added:
```
# Convert Russian domains for example яндекс.рф to xn--d1acpjx3f.xn--p1ai (Punycode)
# If domain in English it return English domain
# You should install idn (apt install idn)
# Convert variables host and domain
host=`echo "$host" | idn`
domain=`echo "$domain" | idn`
```

Now it works fine!

Full script attached!

[ssl_cert_check.zip](https://github.com/selivan/https-ssl-cert-check-zabbix/files/7791146/ssl_cert_check.zip)

**Comment by selivan** [comment]
Hey!

Thank you for bringing up the issue. IDN support added in fe915ce.
