### ISSUE TITLE
Userparams Variables

### ISSUE THREAD

**Issue by dennis-it-net** [selivan/https-ssl-cert-check-zabbix#31]
Hello. What are the variables $1-4 in userparams for? Thanks.

**Comment by dennis-it-net** [comment]
I don't see any description about $1-4 in readme. You mean:

`"<hostname or IP> [port[/starttls protocol]] [domain for TLS SNI] [check timeout (seconds)] [port]"?
`
That's bad documentation man. I love the script, it works. But the documentation is not friendly.

Re the line of the userparams file:

```
# Parameters:
# <hostname or IP> [port[/starttls protocol]] [domain for TLS SNI] [check timeout]
UserParameter=ssl_cert_check_valid[*], /usr/local/bin/ssl_cert_check.sh valid "$1" "$2" "$3" "$4"
UserParameter=ssl_cert_check_expire[*], /usr/local/bin/ssl_cert_check.sh expire "$1" "$2" "$3" "$4"
UserParameter=ssl_cert_list[*],/bin/cat /etc/zabbix/scripts/ssl_cert_list
```

Lines 3-5 should be good, the first two comment lines are just confusing the ones reading it. If it's of no use, don't add it.

Another thing, I don't see how the script works with the zabbix template.

```
advanced - advanced template and userparameter for monitoring of multiple ssl certs per hosts

copy userparameters_ssl_cert_check.conf file into /etc/zabbix/zabbix_agentd.d
copy and modify ssl_cert_list into /etc/zabbix/scripts/ssl_cert_list
import template in zabbix server, assign to host, either run discovery or wait
```

How will the zabbix template work with the script?

**Comment by selivan** [comment]
> description about $1-4 in readme

I assumed that everyone working with Zabbix is familiar with Zabbix and bash argument naming style, where $1 is first function or script argument, $2 is second and so on. So $1 becomes `<hostname or IP>`, $2 becomes `[port[/starttls protocol]]`, etc.

If you can suggest how to make that more clear while keeping the docs concise, I welcome the contribution.

Example templates were not contributed by me, I just brushed them up a little.

`basic` template creates validity and expiration items and triggers for macros `{$EXPIRESWITHIN}`, `{$IPADDR}`, `{$SSLDOMAIN}`, `{$SSLPORT}`, `{$TIMEOUT}`, `{$UPDATEINTERVAL}`. Macros are defined in the template and should be re-defined for host.

`advanced` template uses autodiscovery from file `/etc/zabbix/scripts/ssl_cert_list`, example file provided. Parameter names are self-descriptive. This way a single zabbix host can make checks for multiple SSL endpoints.

I put that in README in `zabbix_template_examples` directory: f9f0912b8440d7212b9d268596a89c1399a619c1
