### ISSUE TITLE
idn: not found

### ISSUE THREAD

**Issue by M4rt1n12** [selivan/https-ssl-cert-check-zabbix#34]
### Environment

`openssl version` says: OpenSSL 1.1.1f  31 Mar 2020

Operating System: Ubuntu Server 20.04 

### Expected Behavior

root@zabbix:~# ./ssl_cert_check.sh expire  xxxxxx.com
82

### Current Behavior

root@zabbix:~# ./ssl_cert_check.sh expire  xxxxxx.com
./ssl_cert_check.sh: line 91: type: idn: not found
82

**Comment by selivan** [comment]
@M4rt1n12 Thanks for the feedback!
