### ISSUE TITLE
Getting error when running scripts with no parameters

### ISSUE THREAD

**Issue by tbblake** [selivan/https-ssl-cert-check-zabbix#43]
When I run the script with no parameters, it spits out a bash error before the usage text:

./ssl_cert_check.sh: line 14: ,: command not found

e.g.
[root@XXXX ~/https-ssl-cert-check-zabbix]# ./ssl_cert_check.sh
-65535
./ssl_cert_check.sh: line 14: ,: command not found

Usage: ssl_cert_check.sh expire|valid|json hostname|ip [port[/starttls protocol]] [domain for TLS SNI] [check_timeout] [tls_version|tls_auto,[self_signed_ok]] [ s_client_option1 ] [ ... ] [ s_client_optionN ]

Script checks SSL certificate expiration and validity for HTTPS.

[port] is optional, default is 443

[starttls protocol] is optional. Use protocol-specific message to switch to TLS communication. See "man s_client" for supported protocols, like: smtp, ftp, ldap

[domain for TLS SNI] is optional, default is hostname

[check_timeout] is optional, default is 5 seconds

[tls_version|tls_auto,[self_signed_ok]] predefined options comma () separated, flag is optional. Set what is needed, no order of parameters is present of the available options below.
  * [tls_version] is optional, no default is set. This will auto negotiate the TLS protocol and choose the TLS version itself. Override the TLS version as you need: tls1, tls1_1, tls1_2, tls1_3. See either the [TLS Version Options](https://www.openssl.org/docs/man3.0/man1/openssl.html) section for the TLS options or use "man s_client" for supported TLS options.

  * [self_signed_ok] is optional. When this flag is set all self-signed certificates will be seen as 'valid'. It will allow OpenSSL return codes 18, 19, 20 and 21. See the 'Diagnostics' section at https://www.openssl.org/docs/man1.0.2/man1/verify.html.

  * [tls_auto] means auto negotiating TLS protocol. That is the default, this option is used as separator if you want to speficy additional s_client options after it.

[ s_client_option1 ] [ ... ] [ s_client_optionN ] is optional. But all other parameters are required to be set. Everything you append after all parameters will be added/appended on the OpenSSL s_client command. See all s_client options at https://www.openssl.org/docs/man1.0.2/man1/s_client.html.

Output:

* expire:

  * N   number of days left before expiration, 0 or negative if expired
  * -65535      failed to get certificate or incorrect parameters

* valid:

  * 1   valid
  * 0   invalid
  * -65535      failed to get certificate or incorrect parameters

* json:

  * JSON object with a summary of the result, which can be used by Zabbix (JSONPath)
        * expire_days: the amount of days before the certificate is expired
        * valid: see 'valid' check
        * return_code: the OpenSSL return code
        * return_text: the OpenSSL return text which gives helpful insights
  * JSON object with the error code and message
        * error_code: -65535
        * error_message: The output of the error message

Return code is always 0, otherwise zabbix agent fails to get item value and triggers would not work. Note: error messages are not printed when running not on a terninal, so that script result from zabbix is always a correct integer.
[root@XXXX ~/https-ssl-cert-check-zabbix]#

**Comment by tbblake** [comment]
Opened PR #45 to fix.

**Comment by selivan** [comment]
Merged #45. Thanks for the contribution! Backticks came from markdown in README )

**Comment by tbblake** [comment]
Happy to help! (an easy fix admittedly....)
