### ISSUE TITLE
when I use zabbix and root users excute the shell script respone the different result

### ISSUE THREAD

**Issue by zhangbei59** [selivan/https-ssl-cert-check-zabbix#49]
![image](https://github.com/selivan/https-ssl-cert-check-zabbix/assets/25737059/9bebc6fc-b006-470b-89ac-192e95d4d043)

The zabbix web is the right result 1,but when I test the script in root user with the same paramter , I got the wrong number 0。

**Comment by zhangbei59** [comment]
My zabbix_agent is running in the zabbix user .

**Comment by selivan** [comment]
Try comparing what 
`echo | openssl s_client -servername "$domain" -verify_hostname "$domain" -connect "$host":443`
says for root user and for zabbix user.

Looks that for whatever reason openssl configuration for root and for regular users differ.

May be `/etc/ssl/openssl.cnf` is readable only for root user or some other reason.

**Comment by zhangbei59** [comment]
The different:

zabbix:
![image](https://github.com/selivan/https-ssl-cert-check-zabbix/assets/25737059/1ccbbf23-227d-4c12-866c-c853d371ba7e)

in root:
![image](https://github.com/selivan/https-ssl-cert-check-zabbix/assets/25737059/c01ed351-63e3-460d-9492-3aeab7c4654c)

**Comment by zhangbei59** [comment]
The /etc/ssl/openssl.cnf file mode is 644

**Comment by selivan** [comment]
Well, for whatever reason openssl works differently from root and from zabbix user. You may try using `strace` to see what differs when calling from root and from zabbix user. Or ask on stackoverflow. Anyway, this is not `ssl_cert_check.sh` script problem.

**Comment by zhangbei59** [comment]
Ok,I will try on stackoverflow.Thanks very much.
