### ISSUE TITLE
read:errno=104 error returned from domain, but check still possible with the command standalone

### ISSUE THREAD

**Issue by sirovstrukelj** [selivan/https-ssl-cert-check-zabbix#5]
So there's a problem with one domain, I cannot share the domain but at the end, the exit code is 104.  The error code at the end of the output with the openssl command is:
read:errno=104

The line i'm referencing: https://github.com/selivan/https-ssl-cert-check-zabbix/blob/46c9188319cb384fe483af44380a64c004dc2835/ssl_cert_check.sh#L61

The command still returns the output and can be parsed to get the expiration date. Of course it failes in the original script, since the if statement is checking that the exit code is 0 and the output is not saved. I have no idea if it's connected to the domain or maybe internal firewall rules. 

I was thinking of checking if the string is (not empty) and ( exit code is 0 or 104)

**Comment by selivan** [comment]
Please post the full `openssl s_client` command line and output with masked domain name.

Generally, if `openssl s_client` returned non-zero, correct result is 'failed to get certificate'.

**Comment by sirovstrukelj** [comment]
So further investigation led that if there is no web server running behind that domain, it will return a non-zero exit code, which is 104.
```
CONNECTED(00000003)

---removed the cert and some other things -----

SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : xxxxxxxxxxxxxxxxxxxxx
    Session-ID: xxxxxxxxxxxxxxxxx
    Session-ID-ctx:
    Master-Key: xxxxxxxxxxxxxxx
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: xxxxxxxxxxxxxxxxxxxxx
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
read:errno=104
```

After this the process exits by itself. 

If i launch this against some other domain, the process does not exit of course and you have to send a piped echo to close it as it is in the script. Of course the nature of the script works okay. Maybe the trigger should be made dependent for the SSL check and see if the web server is actually running. But i'm more interested in what should the correct design choice be in the script.

**Comment by selivan** [comment]
If port is not available on host, the script prints:

```
-65535   // stdout
ERROR: Failed to get certificate    // stderr
```

I think that's clear enough. Finding the reason why it failed to get certificate(no connection, timeout, no SSL on port) is out of purpose for a simple monitoring script.

I close this issue, but if you have a better idea how to handle this - you are welcome to re-open it.
