### ISSUE TITLE
Invalid Date 

### ISSUE THREAD

**Issue by moradmwk** [selivan/https-ssl-cert-check-zabbix#6]
Hello,

We are using Zabbix Server Container based on the official Zabbix Container Image: zabbix/zabbix-server-pgsql:alpine-5.0-latest. 

We are getting following openssl error, while using the "expire" parameter. 

OpenSSL Version is 1.1.1g 21 Apr 2020
```
date: invalid date 'Sep 11 12:00:00 2020 GMT'
-65535
ERROR: Failed to get expire date
```

Thank you for your help in advance.

Cheers,
Marc

**Comment by selivan** [comment]
Turns out that busybox `date` can not parse date format from openssl. Use `apk add coreutils` in busybox-based images like alpine to make the script work.

I added check that shows error if busybox `date` is used.
